import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Product, ProductCategory, ProductResponse } from '../../../models/product.model';

const image = (id: number) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=900&q=85`;

const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    title: 'Cloud Knit Lounge Set',
    description: 'A soft, relaxed two-piece set designed for slow mornings and easy weekends.',
    category: 'womens-dresses',
    price: 68,
    discountPercentage: 15,
    rating: 4.8,
    stock: 18,
    tags: ['comfort', 'new'],
    brand: 'Morrow',
    sku: 'MOR-001',
    weight: 1,
    dimensions: { width: 30, height: 4, depth: 24 },
    warrantyInformation: '30 day guarantee',
    shippingInformation: 'Ships in 2–3 days',
    availabilityStatus: 'In Stock',
    reviews: [],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: { createdAt: '2026-01-01', updatedAt: '2026-02-01', barcode: '100000001', qrCode: '' },
    thumbnail: image(1525507119348),
    images: [image(1525507119348)],
  },
  {
    id: 2,
    title: 'Arc Leather Shoulder Bag',
    description: 'A sculptural everyday bag with considered compartments and a polished finish.',
    category: 'womens-bags',
    price: 124,
    discountPercentage: 10,
    rating: 4.9,
    stock: 9,
    tags: ['leather', 'editor pick'],
    brand: 'Morrow',
    sku: 'MOR-002',
    weight: 1,
    dimensions: { width: 28, height: 20, depth: 12 },
    warrantyInformation: '1 year warranty',
    shippingInformation: 'Ships in 1–2 days',
    availabilityStatus: 'In Stock',
    reviews: [],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: { createdAt: '2026-01-01', updatedAt: '2026-02-01', barcode: '100000002', qrCode: '' },
    thumbnail: image(1548036328),
    images: [image(1548036328)],
  },
  {
    id: 3,
    title: 'Daily Form Sneakers',
    description: 'Lightweight everyday sneakers with a clean profile and all-day cushioning.',
    category: 'womens-shoes',
    price: 92,
    discountPercentage: 8,
    rating: 4.7,
    stock: 24,
    tags: ['everyday', 'best seller'],
    brand: 'Morrow',
    sku: 'MOR-003',
    weight: 2,
    dimensions: { width: 32, height: 14, depth: 20 },
    warrantyInformation: '6 month warranty',
    shippingInformation: 'Ships in 2–3 days',
    availabilityStatus: 'In Stock',
    reviews: [],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: { createdAt: '2026-01-01', updatedAt: '2026-02-01', barcode: '100000003', qrCode: '' },
    thumbnail: image(1542291026),
    images: [image(1542291026)],
  },
  {
    id: 4,
    title: 'Ribbed Essential Tee',
    description: 'A refined wardrobe essential cut from breathable ribbed cotton.',
    category: 'tops',
    price: 38,
    discountPercentage: 12,
    rating: 4.6,
    stock: 42,
    tags: ['essential', 'cotton'],
    brand: 'Morrow',
    sku: 'MOR-004',
    weight: 1,
    dimensions: { width: 25, height: 2, depth: 20 },
    warrantyInformation: '30 day guarantee',
    shippingInformation: 'Ships in 2–3 days',
    availabilityStatus: 'In Stock',
    reviews: [],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: { createdAt: '2026-01-01', updatedAt: '2026-02-01', barcode: '100000004', qrCode: '' },
    thumbnail: image(1521572163474),
    images: [image(1521572163474)],
  },
  {
    id: 5,
    title: 'Linen Studio Shirt',
    description: 'An airy linen shirt for warm days, layered evenings, and everywhere between.',
    category: 'mens-shirts',
    price: 74,
    discountPercentage: 18,
    rating: 4.8,
    stock: 15,
    tags: ['linen', 'summer'],
    brand: 'Morrow',
    sku: 'MOR-005',
    weight: 1,
    dimensions: { width: 30, height: 3, depth: 24 },
    warrantyInformation: '30 day guarantee',
    shippingInformation: 'Ships in 2–3 days',
    availabilityStatus: 'Low Stock',
    reviews: [],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: { createdAt: '2026-01-01', updatedAt: '2026-02-01', barcode: '100000005', qrCode: '' },
    thumbnail: image(1603252110481),
    images: [image(1603252110481)],
  },
  {
    id: 6,
    title: 'Soft Focus Sunglasses',
    description: 'Rounded acetate frames that bring a little softness to bright days.',
    category: 'sunglasses',
    price: 56,
    discountPercentage: 5,
    rating: 4.5,
    stock: 30,
    tags: ['sun', 'accessories'],
    brand: 'Morrow',
    sku: 'MOR-006',
    weight: 1,
    dimensions: { width: 15, height: 5, depth: 4 },
    warrantyInformation: '1 year warranty',
    shippingInformation: 'Ships in 1–2 days',
    availabilityStatus: 'In Stock',
    reviews: [],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: { createdAt: '2026-01-01', updatedAt: '2026-02-01', barcode: '100000006', qrCode: '' },
    thumbnail: image(1511499767150),
    images: [image(1511499767150)],
  },
];

const MOCK_CATEGORIES: ProductCategory[] = [
  'beauty',
  'fragrances',
  'furniture',
  'groceries',
  'home-decoration',
  'kitchen-accessories',
  'laptops',
  'mens-shirts',
  'mens-shoes',
  'mens-watches',
  'mobile-accessories',
  'motorcycle',
  'skin-care',
  'smartphones',
  'sports-accessories',
  'sunglasses',
  'tablets',
  'tops',
  'vehicle',
  'womens-bags',
  'womens-dresses',
  'womens-jewellery',
  'womens-shoes',
  'womens-watches',
].map((slug) => ({
  slug,
  name: slug
    .split('-')
    .map((word) => word[0].toUpperCase() + word.slice(1))
    .join(' '),
  url: `https://dummyjson.com/products/category/${slug}`,
}));

@Injectable({ providedIn: 'root' })
export class ProductService {
  getProducts(): Observable<ProductResponse> {
    return of({
      products: MOCK_PRODUCTS,
      total: MOCK_PRODUCTS.length,
      skip: 0,
      limit: MOCK_PRODUCTS.length,
    });
  }

  getCategories(): Observable<ProductCategory[]> {
    return of(MOCK_CATEGORIES);
  }
}
